services:
  node:
    image: evade84-node
    container_name: evade84-node
    build: ./
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=evade84-node
    env_file:
      - ./.env
    depends_on:
      - mongo
    ports:
      - 80:80
  mongo:
    image: mongo
    container_name: evade84-mongo
    command:
      - '--logpath'
      - '/dev/null'
    volumes:
      - ./mongo:/data/db
