services:
  node:
    image: evade84-node
    container_name: evade-node
    build: ./
    env_file:
      - ./.env
    depends_on:
      - mongo
    ports:
      - 80:80
  mongo:
    image: mongo
    container_name: evade-mongo
    command:
      - '--logpath'
      - '/dev/null'
    volumes:
      - ./mongo:/data/db
